
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&amp;useSSL=true
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  jackson:
      time-zone: GMT+8



springjackson:
  date-format: yyyy-MM-dd HH:mm:ss



server:
  ports: 8080



mybatis:
  mapper-locations: classpath:mybatis/*.xml


redis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-idle: 20
    min-idle: 1
    max-active: 20
    max-wait: 600000
  database: 0


